import '@/styles/globals.css'
import { Inter as FontSans } from 'next/font/google'
import localFont from 'next/font/local'

import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-white font-sans antialiased',
          fontSans.variable,
          fontHeading.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
