export const applicationUIComponents = [
  {
    component: 'button',
    name: 'Buttons',
    files: [
      'components/examples/application-ui/buttons/solid-buttons.tsx',
      'components/examples/application-ui/buttons/outlined-buttons.tsx',
      'components/examples/application-ui/buttons/leading-icon-buttons.tsx',
      'components/examples/application-ui/buttons/trailing-icon-buttons.tsx',
      'components/examples/application-ui/buttons/rounded-buttons.tsx',
      'components/examples/application-ui/buttons/icon-button.tsx',
    ],
    category: 'application/buttons',
    directory: 'components/examples/application-ui/buttons',
  },
  {
    component: 'avatar',
    name: 'Avatars',
    files: [
      'components/examples/application-ui/avatars/avatar-one.tsx',
      'components/examples/application-ui/avatars/avatar-two.tsx',
      'components/examples/application-ui/avatars/avatar-three.tsx',
      'components/examples/application-ui/avatars/avatar-four.tsx',
      'components/examples/application-ui/avatars/avatar-five.tsx',
    ],
    category: 'application/avatars',
    directory: 'components/examples/application-ui/avatars',
  },
  {
    component: 'banner',
    name: 'Banners',
    files: [
      'components/examples/application-ui/banners/banner-one.tsx',
      'components/examples/application-ui/banners/banner-two.tsx',
      'components/examples/application-ui/banners/banner-three.tsx',
      'components/examples/application-ui/banners/banner-four.tsx',
    ],
    category: 'application/banners',
    directory: 'components/examples/application-ui/banners',
  },
  {
    component: 'breadcrumb',
    name: 'Breadcrumbs',
    files: [
      'components/examples/application-ui/breadcrumbs/breadcrumb-one.tsx',
      'components/examples/application-ui/breadcrumbs/breadcrumb-two.tsx',
      'components/examples/application-ui/breadcrumbs/breadcrumb-three.tsx',
      'components/examples/application-ui/breadcrumbs/breadcrumb-four.tsx',
    ],
    category: 'application/breadcrumbs',
    directory: 'components/examples/application-ui/Breadcrumbs',
  },
  {
    component: 'card',
    name: 'Cards',
    files: [
      'components/examples/application-ui/cards/card-one.tsx',
      'components/examples/application-ui/cards/card-two.tsx',
      'components/examples/application-ui/cards/card-three.tsx',
      'components/examples/application-ui/cards/card-four.tsx',
    ],
    category: 'application/cards',
    directory: 'components/examples/application-ui/Cards',
  },
]
