export const marketingComponents = [
  {
    component: 'cta',
    name: 'CTA',
    files: [
      'components/examples/marketing/cta/cta-one.tsx',
      'components/examples/marketing/cta/cta-two.tsx',
      'components/examples/marketing/cta/cta-three.tsx',
      'components/examples/marketing/cta/cta-four.tsx',
    ],
    category: 'marketing/cta',
    directory: 'components/examples/marketing/cta',
  },
  {
    component: 'error',
    name: 'Error',
    files: [
      'components/examples/marketing/error/error-one.tsx',
      'components/examples/marketing/error/error-two.tsx',
      'components/examples/marketing/error/error-three.tsx',
      'components/examples/marketing/error/error-four.tsx',
    ],
    category: 'marketing/error',
    directory: 'components/examples/marketing/error',
  },
  {
    component: 'faq',
    name: 'FAQs',
    files: [
      'components/examples/marketing/faq/faq-one.tsx',
      'components/examples/marketing/faq/faq-two.tsx',
      'components/examples/marketing/faq/faq-three.tsx',
      'components/examples/marketing/faq/faq-four.tsx',
    ],
    category: 'marketing/faq',
    directory: 'components/examples/marketing/faq',
  },
  {
    component: 'feature',
    name: 'Feature',
    files: [
      'components/examples/marketing/feature/feature-one.tsx',
      'components/examples/marketing/feature/feature-two.tsx',
      'components/examples/marketing/feature/feature-three.tsx',
      'components/examples/marketing/feature/feature-four.tsx',
    ],
    category: 'marketing/feature',
    directory: 'components/examples/marketing/feature',
  },
  {
    component: 'footer',
    name: 'Footer',
    files: [
      'components/examples/marketing/footer/footer-one.tsx',
      'components/examples/marketing/footer/footer-two.tsx',
      'components/examples/marketing/footer/footer-three.tsx',
      'components/examples/marketing/footer/footer-four.tsx',
    ],
    category: 'marketing/footer',
    directory: 'components/examples/marketing/footer',
  },
  {
    component: 'testimonial',
    name: 'Testmonials',
    files: [
      'components/examples/marketing/testimonial/testimonial-one.tsx',
      'components/examples/marketing/testimonial/testimonial-two.tsx',
      'components/examples/marketing/testimonial/testimonial-three.tsx',
    ],
    category: 'marketing/testimonial',
    directory: 'components/examples/marketing/testimonial',
  },
  {
    component: 'newsletter',
    name: 'Newsletter',
    files: [
      'components/examples/marketing/newsletter/newsletter-one.tsx',
      'components/examples/marketing/newsletter/newsletter-two.tsx',
      'components/examples/marketing/newsletter/newsletter-three.tsx',
      'components/examples/marketing/newsletter/newsletter-four.tsx',
    ],
    category: 'marketing/newsletter',
    directory: 'components/examples/marketing/newsletter',
  },
  {
    component: 'team',
    name: 'Team',
    files: [
      'components/examples/marketing/team/team-one.tsx',
      'components/examples/marketing/team/team-two.tsx',
      'components/examples/marketing/team/team-three.tsx',
    ],
    category: 'marketing/team',
    directory: 'components/examples/marketing/team',
  },
]
